# Uncomment the next line to define a global platform for your project
# platform :ios, '10.2'

target 'hangTogether' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hangTogether

  pod 'AlamofireImage'
  pod 'Alamofire'
  pod 'ObjectMapper', '~> 2.2'
end
